[LOCAL]
customer.file.path = data/customers.csv
order.file.path = data/orders.csv

[SIT]
customer.file.path = data/customers.csv
order.file.path = data/orders.csv

[OAT]
customer.file.path = data/customers.csv
order.file.path = data/orders.csv

[PROD]
customer.file.path = data/customers.csv
order.file.path = data/orders.csv