[LOCAL]
spark.app.name = "retail_dataset"

[SIT]
spark.app.name = "retail_dataset"

[OAT]
spark.app.name = "retail_dataset"
spark.executor.instances = 10
spark.executor.memory = 2G
spark.executor.cores = 4

[PROD]
spark.app.name = "retail_dataset"
spark.executor.instances = 10
spark.executor.memory = 2G
spark.executor.cores = 2